parameters:
    liuggio_stats_d_client.data_collector.class: AdrienBrault\StatsDCollector\StatsDDataCollector
    liuggio_stats_d_client.collector.increment.class: AdrienBrault\StatsDCollector\Collector\IncrementCollector
    liuggio_stats_d_client.collector.memory.class: AdrienBrault\StatsDCollector\Collector\MemoryCollector
    liuggio_stats_d_client.collector.time.class: AdrienBrault\StatsDCollector\Collector\TimeCollector
    liuggio_stats_d_client.collector.exception.class: AdrienBrault\StatsDCollector\Collector\ExceptionCollector
    liuggio_stats_d_client.collector.doctrine.class: AdrienBrault\StatsDCollector\Collector\DoctrineDbalCollector
    liuggio_stats_d_client.collector.solarium.class: AdrienBrault\StatsDCollector\Collector\SolariumCollector

services:
    liuggio_stats_d_client.data_collector:
        class: %liuggio_stats_d_client.data_collector.class%
        arguments:
            - [] # Collectors
            - [] # Providers

    liuggio_stats_d_client.collector.increment:
        class: %liuggio_stats_d_client.collector.increment.class%
        tags:
            - { name: liuggio_stats_d_client.collector, alias: increment }

    liuggio_stats_d_client.collector.memory:
        class: %liuggio_stats_d_client.collector.memory.class%
        tags:
            - { name: liuggio_stats_d_client.collector, alias: memory }

    liuggio_stats_d_client.collector.time:
        class: %liuggio_stats_d_client.collector.time.class%
        tags:
            - { name: liuggio_stats_d_client.collector, alias: time }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    liuggio_stats_d_client.collector.exception:
        class: %liuggio_stats_d_client.collector.exception.class%
        tags:
            - { name: liuggio_stats_d_client.collector, alias: exception }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    liuggio_stats_d_client.collector.doctrine:
        class: %liuggio_stats_d_client.collector.doctrine.class%
        tags:
            - { name: liuggio_stats_d_client.collector, alias: doctrine }

    liuggio_stats_d_client.collector.solarium:
        class: %liuggio_stats_d_client.collector.solarium.class%
        tags:
            - { name: liuggio_stats_d_client.collector, alias: solarium }
