parameters:
    liuggio_stats_d_client.collector.visitor.class: Liuggio\StatsDClientBundle\StatsCollector\VisitorStatsCollector
    liuggio_stats_d_client.collector.memory.class: Liuggio\StatsDClientBundle\StatsCollector\MemoryStatsCollector
    liuggio_stats_d_client.collector.user.class: Liuggio\StatsDClientBundle\StatsCollector\UserStatsCollector
    liuggio_stats_d_client.collector.exception.class: Liuggio\StatsDClientBundle\StatsCollector\ExceptionStatsCollector
    liuggio_stats_d_client.collector.time.class: Liuggio\StatsDClientBundle\StatsCollector\TimeStatsCollector


services:
    liuggio_stats_d_client.collector.visitor:
        class: %liuggio_stats_d_client.collector.visitor.class%
        calls:
            - ['setOnlyOnMasterResponse', [true]]
        tags:
            - { name: stats_d_collector}

    liuggio_stats_d_client.collector.memory:
        class: %liuggio_stats_d_client.collector.memory.class%
        calls:
            - ['setOnlyOnMasterResponse', [true]]
        tags:
            - { name: stats_d_collector}

    liuggio_stats_d_client.collector.user:
        class: %liuggio_stats_d_client.collector.user.class%
        calls:
            - ['setSecurityContext', [@security.context]]
            - ['setOnlyOnMasterResponse', [true]]
        tags:
            - { name: stats_d_collector}

    liuggio_stats_d_client.collector.exception:
        class: %liuggio_stats_d_client.collector.exception.class%
        calls:
            - ['setOnlyOnMasterResponse', [false]]
        tags:
            - { name: stats_d_collector}

    liuggio_stats_d_client.collector.time:
        class: %liuggio_stats_d_client.collector.time.class%
        calls:
            - ['setOnlyOnMasterResponse', [true]]
        tags:
            - { name: stats_d_collector}

#special connector dbal is also a sqllogger
    liuggio_stats_d_client.collector.dbal:
        class: %liuggio_stats_d_client.collector.dbal.class%
        arguments: ['query']
        calls:
            - ['setOnlyOnMasterResponse', [true]]
        tags:
            - { name: stats_d_collector}
