parameters:
    liuggio_stats_d_client.event_listener.response.class: Liuggio\StatsDClientBundle\EventListener\ResponseListener

services:
    liuggio_stats_d_client.event_listener.response:
        class: %liuggio_stats_d_client.event_listener.response.class%
        arguments:
            - @liuggio_stats_d_client.data_collector
            - @liuggio_stats_d_client.client
        tags:
            - { name: kernel.event_subscriber }
